import { getProducts as getSheetProducts } from "@/lib/google-sheets";
import { getProducts as getDbProducts, createTable, Product } from "@/lib/db";
import ProductCard from "@/components/ProductCard";
import Link from "next/link";
import { ArrowRight, SlidersHorizontal } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function LibreriaPage() {
  let products: Product[] = [];
  try { await createTable(); products = await getDbProducts(); } catch { console.log("No DB configured, falling back to Google Sheets"); }
  if (products.length === 0) products = await getSheetProducts();
  const productsByCategory = products.reduce((acc, product) => { const category = product.category || "Otros"; (acc[category] ||= []).push(product); return acc; }, {} as Record<string, Product[]>);
  const categories = Object.keys(productsByCategory).sort();

  return <div className="min-h-screen bg-[#faf8f6] pb-20"><div className="mx-auto max-w-7xl px-5 pt-8 sm:px-8"><nav className="flex items-center gap-2 text-xs text-[#a8a29d]"><Link href="/" className="transition-colors hover:text-[#ff6b4a]">Inicio</Link><ArrowRight className="size-3" /><span className="text-[#57534e]">Catálogo</span></nav><div className="mt-10 flex flex-col gap-5 border-b border-[#d6d3d1] pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#a68d76]">La colección completa</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.06em] text-[#1c1917] sm:text-5xl">Todo para crear.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-[#78716f]">Explorá nuestra selección de papelería, útiles y objetos para hacer más lindo lo cotidiano.</p></div><div className="flex items-center gap-3"><span className="text-xs text-[#a8a29d]">{products.length} productos</span><button className="inline-flex items-center gap-2 rounded-full border border-[#d6d3d1] px-3 py-2 text-xs font-semibold text-[#57534e] hover:bg-white"><SlidersHorizontal className="size-3.5" /> Filtrar</button></div></div><div className="hide-scrollbar flex gap-2 overflow-x-auto py-6">{["Todos", ...categories].map((category, index) => <a key={category} href={index === 0 ? "#catalogo" : `#${category.toLowerCase().replace(/\s+/g, "-")}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold transition-colors ${index === 0 ? "bg-[#1c1917] text-white" : "border border-[#d6d3d1] text-[#57534e] hover:border-[#ff8265] hover:text-[#e8572f]"}`}>{category}</a>)}</div>{categories.length === 0 ? <div className="rounded-3xl border border-[#e7e5e4] bg-white py-20 text-center"><h2 className="font-semibold text-[#1c1917]">No hay productos disponibles</h2><p className="mt-2 text-sm text-[#78716f]">Volvé pronto para descubrir novedades.</p></div> : <div id="catalogo" className="flex flex-col gap-16">{categories.map((category) => <section key={category} id={category.toLowerCase().replace(/\s+/g, "-")}><div className="mb-7 flex items-center justify-between"><div className="flex items-center gap-3"><h2 className="text-xl font-semibold tracking-[-0.03em] text-[#1c1917]">{category}</h2><span className="rounded-full bg-[#f5f1ec] px-2.5 py-1 text-[10px] font-semibold text-[#8b6f57]">{productsByCategory[category].length}</span></div><span className="hidden text-xs text-[#a8a29d] sm:block">Selección Bia</span></div><div className="grid grid-cols-2 gap-x-4 gap-y-10 sm:grid-cols-3 lg:grid-cols-4 lg:gap-x-6">{productsByCategory[category].map((product) => <ProductCard key={product.id} product={product} />)}</div></section>)}</div>}</div></div>;
}
